### ISSUE TITLE
Entscheidung für erste Bewässerungsarchitektur

### ISSUE THREAD

**Issue by oliveraustria** [oh-balcony/oh-balcony.github.io#3]
- Wassertank, Pumpe
- Wasserverteilung für Schlauchsysteme
- 1 Digitalausgang für Pumpansteuerung
- 1 Analogeingang für Feuchtigkeitssensor
- 1 Digitaleingang für Füllstandsensor-Tonne

**Comment by Bronkoknorb** [comment]
Hab begonnen die Komponenten unseres Systems hier zu beschreiben:
https://github.com/oh-balcony/oh-balcony.github.io/wiki/Komponenten
